# Generated by Django 3.1.6 on 2021-02-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messages', '0003_auto_20210206_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalmessage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='globalmessage',
            name='video',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='image',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='video',
        ),
        migrations.AddField(
            model_name='globalmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='messages',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
