# Generated by Django 3.1.6 on 2021-02-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messages', '0005_auto_20210206_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
