# Generated by Django 3.1.6 on 2021-02-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messages', '0006_messages_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='userImage',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
